use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    generate_builtin_tool_registry();
    tauri_build::build()
}

fn generate_builtin_tool_registry() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let tools_dir = manifest_dir.join("src").join("llm").join("tools");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let registry_path = out_dir.join("builtin_tool_registry.rs");

    println!("cargo:rerun-if-changed={}", tools_dir.display());

    let mut packages = Vec::new();
    for entry in fs::read_dir(&tools_dir).expect("read tool packages") {
        let entry = entry.expect("read tool package entry");
        let package_dir = entry.path();
        if !package_dir.is_dir() {
            continue;
        }

        let package_name = entry
            .file_name()
            .into_string()
            .expect("tool package name must be valid UTF-8");

        if matches!(package_name.as_str(), "shared" | "NewToolTemplate") {
            continue;
        }

        let mod_rs = package_dir.join("mod.rs");
        if !mod_rs.exists() {
            continue;
        }

        println!("cargo:rerun-if-changed={}", mod_rs.display());

        let module_source = fs::read_to_string(&mod_rs)
            .unwrap_or_else(|error| panic!("read {}: {error}", mod_rs.display()));
        if !module_source.contains("pub(crate) fn registrations") {
            panic!(
                "tool package {} must export pub(crate) fn registrations()",
                package_name
            );
        }

        packages.push((package_name_to_module_ident(&package_name), mod_rs));
    }

    packages.sort_by(|left, right| left.0.cmp(&right.0));

    if packages.is_empty() {
        panic!("no built-in tool packages exported registrations()");
    }

    let mut generated = String::from("// @generated by build.rs; do not edit by hand.\n\n");
    for (module_ident, mod_rs) in &packages {
        generated.push_str(&format!(
            "#[path = r#\"{}\"#]\nmod {};\n",
            mod_rs.display(),
            module_ident
        ));
    }

    generated.push_str("\nfn builtin_tool_registrations() -> Vec<ToolRegistration> {\n");
    generated.push_str("    let mut tools = Vec::new();\n");
    for (module_ident, _) in &packages {
        generated.push_str(&format!(
            "    tools.extend({module_ident}::registrations());\n"
        ));
    }
    generated.push_str("    tools\n}\n");

    fs::write(&registry_path, generated)
        .unwrap_or_else(|error| panic!("write {}: {error}", registry_path.display()));
}

fn package_name_to_module_ident(package_name: &str) -> String {
    let chars: Vec<char> = package_name.chars().collect();
    let mut ident = String::with_capacity(package_name.len() + 4);

    for (index, ch) in chars.iter().copied().enumerate() {
        if ch.is_ascii_uppercase() {
            let prev = index.checked_sub(1).map(|prev| chars[prev]);
            let next = chars.get(index + 1).copied();
            let starts_new_word = index > 0
                && (prev.is_some_and(|prev| prev.is_ascii_lowercase() || prev.is_ascii_digit())
                    || next.is_some_and(|next| next.is_ascii_lowercase()));
            if starts_new_word {
                ident.push('_');
            }
            ident.push(ch.to_ascii_lowercase());
        } else {
            ident.push(ch);
        }
    }

    ident
}
